/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        abyss: "#050505",
        background: "#14140f",
        surface: "#14140f",
        "surface-dim": "#14140f",
        "surface-bright": "#3a3933",
        "surface-container-lowest": "#0f0e0a",
        "surface-container-low": "#1c1c16",
        "surface-container": "#20201a",
        "surface-container-high": "#2b2a24",
        "surface-container-highest": "#36352f",
        "surface-variant": "#36352f",
        "on-background": "#e6e2d9",
        "on-surface": "#e6e2d9",
        "on-surface-variant": "#d0c5af",
        outline: "#99907c",
        "outline-variant": "#4d4635",
        primary: "#f2ca50",
        "primary-container": "#d4af37",
        secondary: "#e2c559",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "surface-tint": "#e9c349",
        "gold-glow": "rgba(212,175,55,0.15)",
        // Extended Aethelgard tones
        structure: "#101010",
        glass: "rgba(24, 24, 24, 0.75)",
      },
      fontFamily: {
        serif: ["Bodoni Moda", "serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-hero": ["Bodoni Moda", "serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "meta-technical": ["JetBrains Mono", "monospace"],
        "quest-stat": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-hero": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "meta-technical": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "500" }],
        "quest-stat": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      spacing: {
        unit: "4px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-lg": "32px",
        "margin-safe": "64px",
        "section-gap": "120px",
      },
      borderRadius: {
        DEFAULT: "2px",
        sm: "2px",
        lg: "4px",
        xl: "8px",
        full: "9999px",
      },
      boxShadow: {
        "gold-glow": "0 0 15px rgba(212,175,55,0.4)",
        "gold-glow-subtle": "0 0 15px rgba(212,175,55,0.15)",
        "portal-glow": "0 0 100px 20px rgba(242, 202, 80, 0.3)",
        "gold-border-inset": "inset 0 0 10px rgba(242, 202, 80, 0.1)",
      },
    },
  },
  plugins: [],
};
