import { Project } from "@/types/project";

export const projectsData: Project[] = [
  {
    id: "proj-001",
    slug: "kinetic-monolith",
    title: "Kinetic Monolith",
    artifactNumber: 1,
    year: 2024,
    category: "Computational Physics Sculpture",
    description: "A computational physics sculpture exploring kinetic motion.",
    thumbnail: { src: "/images/projects/kinetic-monolith.jpg", alt: "Kinetic Monolith computational physics sculpture", type: "image" },
    heroImage: { src: "/images/projects/kinetic-monolith-hero.jpg", alt: "Kinetic Monolith Hero", type: "image" },
    technologies: [
      { name: "React" },
      { name: "TypeScript" },
      { name: "Three.js" },
    ],
    problem: "TODO: PROBLEM DESCRIPTION",
    approach: "TODO: APPROACH DESCRIPTION",
    challenges: ["TODO: CHALLENGE 1"],
    solutions: ["TODO: SOLUTION 1"],
    results: "TODO: RESULTS",
    gallery: [{ src: "/images/projects/kinetic-monolith-hero.jpg", alt: "Gallery view 1", type: "image" }],
    liveUrl: "https://example.com/kinetic-monolith",
    sourceUrl: "https://github.com/example/kinetic-monolith",
    featured: true,
    sortOrder: 10,
  },
  {
    id: "proj-002",
    slug: "geometric-luminescence",
    title: "Geometric Luminescence",
    artifactNumber: 2,
    year: 2025,
    category: "Volumetric Light Installation",
    description: "Spatial volumetric light installation.",
    thumbnail: { src: "/images/projects/geometric-luminescence.jpg", alt: "Geometric Luminescence spatial volumetric light installation", type: "image" },
    heroImage: { src: "/images/projects/geometric-luminescence-hero.jpg", alt: "Geometric Luminescence Hero", type: "image" },
    technologies: [
      { name: "Next.js" },
      { name: "WebGL" },
    ],
    problem: "TODO: PROBLEM DESCRIPTION",
    approach: "TODO: APPROACH DESCRIPTION",
    challenges: ["TODO: CHALLENGE 1", "TODO: CHALLENGE 2"],
    solutions: ["TODO: SOLUTION 1"],
    results: "TODO: RESULTS",
    gallery: [{ src: "/images/projects/kinetic-monolith-hero.jpg", alt: "Gallery view 1", type: "image" }],
    featured: false,
    sortOrder: 20,
  },
  {
    id: "proj-003",
    slug: "wireframe-labyrinth",
    title: "Wireframe Labyrinth",
    artifactNumber: 3,
    year: 2023,
    category: "Algorithmic Space Installation",
    description: "An algorithmic space installation generating non-orientable topological surfaces.",
    thumbnail: { src: "/images/projects/wireframe-labyrinth.jpg", alt: "Wireframe Labyrinth algorithmic space installation", type: "image" },
    heroImage: { src: "/images/projects/wireframe-labyrinth-hero.jpg", alt: "Wireframe Labyrinth Hero", type: "image" },
    technologies: [
      { name: "WebAudio API" },
      { name: "Canvas" },
    ],
    problem: "TODO: PROBLEM DESCRIPTION",
    approach: "TODO: APPROACH DESCRIPTION",
    challenges: ["TODO: CHALLENGE 1"],
    solutions: ["TODO: SOLUTION 1"],
    results: "TODO: RESULTS",
    gallery: [{ src: "/images/projects/kinetic-monolith-hero.jpg", alt: "Gallery view 1", type: "image" }],
    featured: false,
    sortOrder: 30,
  },
  {
    id: "proj-004",
    slug: "acoustic-sculpture",
    title: "Acoustic Sculpture",
    artifactNumber: 4,
    year: 2025,
    category: "Acoustic Displacement Fields",
    description: "Acoustic displacement fields modeled on physical materials through compute shaders.",
    thumbnail: { src: "/images/projects/acoustic-sculpture.jpg", alt: "Acoustic kinetic sculpture", type: "image" },
    heroImage: { src: "/images/projects/acoustic-sculpture.jpg", alt: "Acoustic kinetic sculpture Hero", type: "image" },
    technologies: [
      { name: "Compute Shaders" },
      { name: "GLSL" },
    ],
    problem: "TODO: PROBLEM DESCRIPTION",
    approach: "TODO: APPROACH DESCRIPTION",
    challenges: ["TODO: CHALLENGE 1"],
    solutions: ["TODO: SOLUTION 1"],
    results: "TODO: RESULTS",
    gallery: [{ src: "/images/projects/kinetic-monolith-hero.jpg", alt: "Gallery view 1", type: "image" }],
    featured: false,
    sortOrder: 40,
  }
];
